--1. example 계정을 생성하고 개체생성 ,변경 , 제거권한과 , DB 연결 권한을 추가하고 example2 계정을 생성하고 DB연결 권한과
--   view 생성 권한을 추가한다.

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER example IDENTIFIED BY "example1234";

CREATE USER example2 IDENTIFIED BY "example1234";

GRANT CREATE SESSION TO example;--DB 연결 권한

GRANT CREATE SESSION TO example2; --DB 연결 권한

GRANT CREATE TABLE TO example; -- 테이블 개체 생성 권한

GRANT CREATE VIEW TO example2; -- VIEW 생성 권한 example2 done.

ALTER USER example DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM; -- 공간 할당

GRANT RESOURCE TO example;

GRANT ALTER ANY TABLE TO example; --변경 권한

GRANT DROP ANY TABLE TO example; --제거 권한

--2. example2 계정의 DB연결 권한을 회수 후 계정 삭제한다.

REVOKE CREATE SESSION FROM example2; -- example2 계정 권한 회수

alter session set "_oracle_script"=true;

select sid, serial#, username,status from v$session where username = 'EXAMPLE2';

alter system kill session '8,19985';

alter system kill session '134,11209';

DROP USER example2 CASCADE;

--03.example계정으로 접속해서 테이블 정의서를 참고하여 MEMBER테이블과 BOARD 테이블을 생성한다.

CREATE TABLE "MEMBER"(
 MEMBER_NO NUMBER PRIMARY KEY,
 MEMBER_ID VARCHAR2(30) NOT NULL,
 MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
 PHONE_NUMBER VARCHAR2(20),
 DELETE_YN CHAR(1) DEFAULT 'N' CHECK(DELETE_YN IN('Y','N'))
);

CREATE TABLE "BOARD"(
BOARD_NO NUMBER NOT NULL,
BOARD_TITLE VARCHAR2(300) NOT NULL,
BOARD_CONTENT VARCHAR2(4000) NOT NULL,
BOARD_WRITER NUMBER REFERENCES "MEMBER"(MEMBER_NO),
CREATE_DATE DATE DEFAULT SYSDATE,
PRIMARY KEY(BOARD_NO)
);

CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100 
INCREMENT BY 100 
NOMINVALUE    
NOCYCLE       
NOCACHE;

CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1 -- 100번부터 시작
INCREMENT BY 1 -- 5씩 증가
NOMINVALUE    
NOCYCLE       
NOCACHE;

COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN "MEMBER".PHONE_NUMBER IS '전화번호';


INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO.NEXTVAL,'step1','step11','-',DEFAULT);
INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO.NEXTVAL,'step2','step22','010-1111-2222',DEFAULT);
INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO.NEXTVAL,'step3','step33','-',DEFAULT);

COMMENT ON COLUMN "BOARD".BOARD_NO IS '글번호';
COMMENT ON COLUMN "BOARD".BOARD_TITLE IS '글제목';
COMMENT ON COLUMN "BOARD".BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN "BOARD".BOARD_WRITER IS '작성자번호';
COMMENT ON COLUMN "BOARD".CREATE_DATE IS '작성일자';


INSERT INTO "BOARD"
VALUES (SEQ_BOARD_NO.NEXTVAL,'첫 글','스텝평가',100,DEFAULT);
INSERT INTO "BOARD"
VALUES (SEQ_BOARD_NO.NEXTVAL,'두 번째 글','재밌다',300,DEFAULT);
INSERT INTO "BOARD"
VALUES (SEQ_BOARD_NO.NEXTVAL,'세 번째 글','하하하',200,DEFAULT);

SELECT BOARD_NO 글번호,BOARD_TITLE 제목,BOARD_CONTENT 내용,MEMBER_ID 작성자,TO_CHAR(CREATE_DATE,'YYYY-MM-DD') 작성일자
FROM "MEMBER"
LEFT JOIN "BOARD" ON(BOARD_WRITER = MEMBER_NO)
ORDER BY 글번호 DESC;